# Generated by Django 4.1.4 on 2022-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmail", "0007_loggedemailmessage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loggedmessage",
            index=models.Index(
                fields=["to", "subject"], name="appmail_log_to_a7e0dd_idx"
            ),
        ),
    ]
