# Generated by Django 6.0 on 2026-01-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmail", "0008_add_logged_message_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="emailtemplate",
            constraint=models.UniqueConstraint(
                fields=("name", "language", "version"),
                name="unique_email_template_name_language_version",
            ),
        ),
    ]
